site_name: DISMTools Help Documentation
theme:
  name: readthedocs
  sticky_navigation: False
  prev_next_buttons_location: none
  logo: logo.png
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math  
nav:
- Home: index.md
- Getting started: getting_started/start.md
- What's new: whats_new/highlights.md
- Image tasks:
  - Overview: img_tasks/img_tasks.md
  - Online installation management mode: img_tasks/online_inst_mgmt.md
  - Offline installation management mode: img_tasks/offline_inst_mgmt.md
  - Image management:
    - Appending to an image: img_tasks/mgmt/append_image.md
    - Applying an image: img_tasks/mgmt/apply_image.md
    - Capturing an image: img_tasks/mgmt/capture_image.md
    - Removing volume images from an image file: img_tasks/mgmt/delete_image.md
    - Exporting a Windows image: img_tasks/mgmt/export_image.md
    - Listing the contents of Windows images: img_tasks/mgmt/list_image.md
    - Mounting an image: img_tasks/mgmt/mount_image.md
    - Remounting an image: img_tasks/mgmt/remount_image.md
    - Splitting an image: img_tasks/mgmt/split_image.md
    - Unmounting an image: img_tasks/mgmt/unmount_image.md
    - Image information dialogs:
      - Overview: img_tasks/info/infodlgs.md
      - Image file information: img_tasks/info/img_info.md
      - Package information: img_tasks/info/pkg_info.md
      - Feature information: img_tasks/info/feat_info.md
      - AppX package information: img_tasks/info/appxpkg_info.md
      - Capability information: img_tasks/info/cap_info.md
      - Driver information: img_tasks/info/drv_info.md
      - Windows PE configuration information: img_tasks/info/winpe_info.md
  - OS packages:
    - Overview: img_tasks/packages/pkgs.md
    - Adding packages: img_tasks/packages/add_package.md
    - Removing packages: img_tasks/packages/remove_package.md
  - Features:
    - Overview: img_tasks/features/features.md
    - Enabling features: img_tasks/features/enable_feature.md
    - Disabling features: img_tasks/features/disable_feature.md
  - AppX packages:
    - Overview: img_tasks/appx/appx.md
    - Adding AppX packages: img_tasks/appx/add_provisionedappxpackage.md
    - Removing AppX packages: img_tasks/appx/remove_provisionedappxpackage.md
  - Edition servicing:
    - Overview: img_tasks/editions/editions.md
    - Upgrading an image to a higher edition: img_tasks/editions/set_edition.md
    - Setting the product key: img_tasks/editions/set_productkey.md
  - Languages and regional servicing:
    - Setting keyboard layered drivers: img_tasks/langs/set_layereddriver.md
  - Capabilities:
    - Overview: img_tasks/capabilities/caps.md
    - Adding capabilities: img_tasks/capabilities/add_capability.md
    - Removing capabilities: img_tasks/capabilities/remove_capability.md
  - Drivers:
    - Overview: img_tasks/drivers/drvs.md
    - Adding drivers: img_tasks/drivers/add_driver.md
    - Exporting drivers: img_tasks/drivers/export_driver.md
    - Importing drivers: img_tasks/drivers/import_driver.md
    - Removing drivers: img_tasks/drivers/remove_driver.md
- Tools:
  - Mounted image manager: img_tasks/tools/mimgmgr.md
  - Image conversion: img_tasks/tools/wim2esd.md
  - SWM file merger: img_tasks/tools/swm2wim.md
  - DISM Configuration List Editor: img_tasks/tools/configlisteditor.md
  - ISO creation tools:
    - Overview: img_tasks/tools/isocreator.md
    - Creating ISO files: img_tasks/tools/isocreator/isocreate.md
    - Installing the operating system:
      - Local installations: img_tasks/tools/isocreator/install/localinstall.md
      - Network-based installations:
        - Overview: img_tasks/tools/isocreator/install/netinst/pxehelpers.md
        - Creating a basic network setup (Hyper-V): img_tasks/tools/isocreator/install/netinst/setup.md
        - Windows Deployment Services (WDS) Helper: img_tasks/tools/isocreator/install/netinst/wds.md
      - External Tools:
        - Driver Installation Module: img_tasks/tools/isocreator/exttools/dim.md
        - Extensibility Suite: img_tasks/tools/isocreator/exttools/dtpe_es.md
        - SysPrep Preparation Tool: img_tasks/tools/isocreator/exttools/sysprep.md
  - Image registry control panel: img_tasks/tools/regcpl.md
  - Unattended answer files:
    - Overview: img_tasks/unattend/unattend.md
    - Unattended answer file manager: img_tasks/unattend/unatt_man.md
    - Unattended answer file creator: img_tasks/unattend/unatt_create.md
    - Applying unattended answer files: img_tasks/unattend/unatt_apply.md
  - External tools:
    - Creating your themes: img_tasks/exttools/themedesigner.md
    - Viewing diagnostic logs: img_tasks/exttools/dynaviewer.md