site_name: DISMTools Help Documentation
theme:
  name: readthedocs
  sticky_navigation: False
  prev_next_buttons_location: none
  logo: logo.png

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math

use_directory_urls: false

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: es 
          name: Español
          build: true
      assets: 
        res: res
      nav_translations:
        es:
          # Root Level
          Home: Inicio
          Getting started: Comienzo
          What's new: Novedades
          Image tasks: Operaciones con imágenes
          Tools: Herramientas
          External tools: Herramientas externas
          
          # Image Tasks Sub-menu
          Overview: Resumen
          Online installation management mode: Modo de administración de imágenes en línea
          Offline installation management mode: Modo de administración de imágenes fuera de línea
          Image management: Administración de imágenes
          Appending to an image: Anexar a una imagen
          Applying an image: Aplicar una imagen
          Capturing an image: Capturar una imagen
          Removing volume images from an image file: Eliminar archivos de volumen de un archivo de imagen
          Exporting a Windows image: Exportar una imagen de Windows
          Listing the contents of Windows images: Listar contenidos de imágenes de Windows
          Mounting an image: Montar una imagen
          Remounting an image: Remontar una imagen
          Splitting an image: Dividir una imagen
          Unmounting an image: Desmontar una imagen
          
          # Info Dialogs
          Image information dialogs: Diálogos de información de imagen
          Image file information: Información de archivos de imagen
          Package information: Información de paquetes
          Feature information: Información de características
          AppX package information: Información de paquetes AppX
          Capability information: Información de funcionalidades
          Driver information: Información de controladores
          Windows PE configuration information: Información de configuración de Windows PE
          
          # Packages & Features
          OS packages: Paquetes del sistema operativo
          Adding packages: Añadir paquetes
          Removing packages: Eliminar paquetes
          Features: Características
          Enabling features: Habilitar características
          Disabling features: Deshabilitar características
          
          # AppX
          AppX packages: Paquetes AppX
          Adding AppX packages: Añadir paquetes AppX
          Removing AppX packages: Eliminar paquetes AppX

          # Editions & Langs
          Edition servicing: Servicio de ediciones
          Upgrading an image to a higher edition: Actualizar imagen a una edición superior
          Setting the product key: Establecer la clave de producto
          Languages and regional servicing: Servicio de idiomas y regional
          Setting keyboard layered drivers: Establecer controladores de capas de teclado

          # Capabilities & Drivers
          Capabilities: Funcionalidades
          Adding capabilities: Añadir funcionalidades
          Removing capabilities: Eliminar funcionalidades
          Drivers: Controladores
          Adding drivers: Añadir controladores
          Exporting drivers: Exportar controladores
          Importing drivers: Importar controladores
          Removing drivers: Eliminar controladores

          # Tools section
          Mounted image manager: Administrador de imágenes montadas
          Image conversion: Conversión de imágenes
          SWM file merger: Combinación de archivos SWM
          DISM Configuration List Editor: Editor de listas de configuración de DISM
          ISO creation tools: Herramientas de creación de ISO
          Creating ISO files: Creación de archivos ISO
          Installing the operating system: Instalación del sistema operativo
          Local installations: Instalaciones locales
          Network-based installations: Instalaciones basadas en red
          Windows Deployment Services (WDS) Helper: Ayudante de WDS
          Driver Installation Module: Módulo de instalación de controladores
          Extensibility Suite: Suite de extensibilidad
          SysPrep Preparation Tool: Herramienta de preparación de SysPrep
          Image registry control panel: Panel de control del registro de imágenes
          System service manager: Administrador de servicios del sistema
          System environment variable manager: Administrador de variables de entorno del sistema
          Unattended answer files: Archivos de respuesta desatendida
          Unattended answer file manager: Administrador de archivos de respuesta desatendida
          Unattended answer file creator: Creador de archivos de respuesta desatendida
          Applying unattended answer files: Aplicar archivos de respuesta desatendida
          
          # External tools
          Creating your themes: Creando tus temas
          Viewing diagnostic logs: Ver registros de diagnóstico
      fallback_to_default: true

nav:
- Home: index.md
- Getting started: 
  - Overview: getting_started/start.md
  - MSMG Migration: getting_started/msmg_migration.md
- What's new: whats_new/highlights.md
- Image tasks:
  - Overview: img_tasks/img_tasks.md
  - Online installation management mode: img_tasks/online_inst_mgmt.md
  - Offline installation management mode: img_tasks/offline_inst_mgmt.md
  - Image management:
    - Appending to an image: img_tasks/mgmt/append_image.md
    - Applying an image: img_tasks/mgmt/apply_image.md
    - Capturing an image: img_tasks/mgmt/capture_image.md
    - Removing volume images from an image file: img_tasks/mgmt/delete_image.md
    - Exporting a Windows image: img_tasks/mgmt/export_image.md
    - Listing the contents of Windows images: img_tasks/mgmt/list_image.md
    - Mounting an image: img_tasks/mgmt/mount_image.md
    - Remounting an image: img_tasks/mgmt/remount_image.md
    - Splitting an image: img_tasks/mgmt/split_image.md
    - Unmounting an image: img_tasks/mgmt/unmount_image.md
    - Image information dialogs:
      - Overview: img_tasks/info/infodlgs.md
      - Image file information: img_tasks/info/img_info.md
      - Package information: img_tasks/info/pkg_info.md
      - Feature information: img_tasks/info/feat_info.md
      - AppX package information: img_tasks/info/appxpkg_info.md
      - Capability information: img_tasks/info/cap_info.md
      - Driver information: img_tasks/info/drv_info.md
      - Windows PE configuration information: img_tasks/info/winpe_info.md
  - OS packages:
    - Overview: img_tasks/packages/pkgs.md
    - Adding packages: img_tasks/packages/add_package.md
    - Removing packages: img_tasks/packages/remove_package.md
  - Features:
    - Overview: img_tasks/features/features.md
    - Enabling features: img_tasks/features/enable_feature.md
    - Disabling features: img_tasks/features/disable_feature.md
  - AppX packages:
    - Overview: img_tasks/appx/appx.md
    - Adding AppX packages: img_tasks/appx/add_provisionedappxpackage.md
    - Removing AppX packages: img_tasks/appx/remove_provisionedappxpackage.md
  - Edition servicing:
    - Overview: img_tasks/editions/editions.md
    - Upgrading an image to a higher edition: img_tasks/editions/set_edition.md
    - Setting the product key: img_tasks/editions/set_productkey.md
  - Languages and regional servicing:
    - Setting keyboard layered drivers: img_tasks/langs/set_layereddriver.md
  - Capabilities:
    - Overview: img_tasks/capabilities/caps.md
    - Adding capabilities: img_tasks/capabilities/add_capability.md
    - Removing capabilities: img_tasks/capabilities/remove_capability.md
  - Drivers:
    - Overview: img_tasks/drivers/drvs.md
    - Adding drivers: img_tasks/drivers/add_driver.md
    - Exporting drivers: img_tasks/drivers/export_driver.md
    - Importing drivers: img_tasks/drivers/import_driver.md
    - Removing drivers: img_tasks/drivers/remove_driver.md
- Tools:
  - Mounted image manager: img_tasks/tools/mimgmgr.md
  - Image conversion: img_tasks/tools/wim2esd.md
  - SWM file merger: img_tasks/tools/swm2wim.md
  - DISM Configuration List Editor: img_tasks/tools/configlisteditor.md
  - ISO creation tools:
    - Overview: img_tasks/tools/isocreator.md
    - Creating ISO files: img_tasks/tools/isocreator/isocreate.md
    - Installing the operating system:
      - Local installations: img_tasks/tools/isocreator/install/localinstall.md
      - Network-based installations:
        - Overview: img_tasks/tools/isocreator/install/netinst/pxehelpers.md
        - Creating a basic network setup (Hyper-V): img_tasks/tools/isocreator/install/netinst/setup.md
        - Windows Deployment Services (WDS) Helper: img_tasks/tools/isocreator/install/netinst/wds.md
      - External Tools:
        - Driver Installation Module: img_tasks/tools/isocreator/exttools/dim.md
        - Extensibility Suite: img_tasks/tools/isocreator/exttools/dtpe_es.md
        - SysPrep Preparation Tool: img_tasks/tools/isocreator/exttools/sysprep.md
      - Command-line:
        - Overview: img_tasks/tools/isocreator/cmdline/cmdline.md
        - Administration Script Reference: img_tasks/tools/isocreator/cmdline/scriptref.md
  - Image registry control panel: img_tasks/tools/regcpl.md
  - System service manager: img_tasks/tools/servicemgr.md
  - System environment variable manager: img_tasks/tools/envvarmgr.md
  - Unattended answer files:
    - Overview: img_tasks/unattend/unattend.md
    - Unattended answer file manager: img_tasks/unattend/unatt_man.md
    - Unattended answer file creator: img_tasks/unattend/unatt_create.md
    - Applying unattended answer files: img_tasks/unattend/unatt_apply.md
  - External tools:
    - Creating your themes: img_tasks/exttools/themedesigner.md
    - Viewing diagnostic logs: img_tasks/exttools/dynaviewer.md